export type Problem = {
    id: string;
    title: string;
    difficulty: string;
    category: string;
    order: number;
    videoId: string;
}

export const problems : Problem[] = [
    {
        id: "two-sum",
        title: " Two sum",
        difficulty: "Easy",
        category: "Array",
        order: 1,
        videoId: "8_Z4CBA58m8",
    },
    {
        id: "reverse-linked-list",
        title: "Reverse Linked List",
        difficulty: "Hard",
        category: "Linked List",
        order: 2,
        videoId: "1s_PwSyye8s",
    },
    {
        id: "jump-game",
        title: "Jump Game",
        difficulty: "Medium",
        category: "Dynamic Programming",
        order: 3,
        videoId: "",
    },
    {
        id: "valid-parentheses",
        title: "Valid Parentheses",
        difficulty: "Easy",
        category: "Stack",
        order: 4,
        videoId: "",
    },
    {
        id: "search-a-2d-matrix",
        title: "Search a 2D Matrix",
        difficulty: "Medium",
        category: "Binary Search",
        order: 5,
        videoId: "",
    },
    {
        id: "container-with-most-water",
        title: "Container With Most Water",
        difficulty: "Medium",
        category: "Two Pointers",
        order: 6,
        videoId: "",
    },
    {
        id: "merge-intervals",
        title: "Merger Intervals",
        difficulty: "Medium",
        category: "Intervals",
        order: 7,
        videoId: "",
    },
    {
        id: "maximum-depth-of-binary-tree",
        title: "Maximum Depth of Binary Tree",
        difficulty: "Medium",
        category: "Tree",
        order: 8,
        videoId: "",
    },
    
    {
        id: "subsets",
        title: "Subsets",
        difficulty: "Medium",
        category: "Array",
        order: 9,
        videoId: "",
    },
    {
        id: "minimum-element",
        title: "MinimumElement Without Sorting",
        difficulty: "Medium",
        category: "Array",
        order: 10,
        videoId: "",
    },
    {
        id: "first-negative-integer",
        title: "First negative integer",
        difficulty: "Medium",
        category: "Backtracking",
        order: 11,
        videoId: "",
    },
    {
        id: "area-of-triangle",
        title: "Area of Triangle",
        difficulty: "Easy",
        category: "Number",
        order: 12,
        videoId: "",
    },
    {
        id: "composite",
        title: "Composite",
        difficulty: "Easy",
        category: "Number",
        order: 13,
        videoId: "",
    },
    {
        id: "between-number",
        title: "Between Number",
        difficulty: "Easy",
        category: "Number",
        order: 14,
        videoId: "",
    },
    {
        id: "shortest-word-distance",
        title: "Shortest Word Distance",
        difficulty: "Medium",
        category: "Array",
        order: 15,
        videoId: "",
    },
    {
        id: "classiffy-triangle",
        title: "Classify Triangle by length",
        difficulty: "Medium",
        category: "Number",
        order: 16,
        videoId: "",
    },
    {
        id: "fauemail",
        title: "Find All Unique Domains In Email",
        difficulty: "Medium",
        category: "Array",
        order: 17,
        videoId: "",
    },
    {
        id: "highest-salary",
        title: "Highest Salaries Difference",
        difficulty: "Medium",
        category: "Number",
        order: 18,
        videoId: "",
    },
    {
        id: "hastag",
        title: "Find Trending Hashtag",
        difficulty: "Hard",
        category: "String Manipulation",
        order: 19,
        videoId: "",
    },
    {
        id: "friday-purchase",
        title: "Friday Purchase",
        difficulty: "Hard",
        category: "Array",
        order: 20,
        videoId: "",
    },

]